# Railway Nixpacks configuration
[phases.setup]
nixPkgs = ["python311", "ffmpeg", "libsndfile"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -e ."]

[phases.build]
cmds = []

[start]
cmd = "uvicorn src.app.web:app --host 0.0.0.0 --port $PORT"
