services:
  - type: web
    name: ai-video-generator
    env: docker
    repo: https://github.com/jeff99jackson99/ai-video-generator
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: APP_HOST
        value: 0.0.0.0
      - key: APP_PORT
        value: 10000
      - key: DEBUG
        value: false
      - key: MAX_CONCURRENT_JOBS
        value: 1
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PEXELS_API_KEY
        sync: false
      - key: UNSPLASH_API_KEY
        sync: false
      - key: PIXABAY_API_KEY
        sync: false

